# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='', help_text='博客标识', max_length=100, verbose_name='博客标识')),
                ('nickname', models.CharField(default='', help_text='昵称', max_length=100, verbose_name='昵称')),
                ('suggestType', models.IntegerField(choices=[(2, '纠正'), (1, '建议')], default=1, help_text='建议类型', verbose_name='建议类型')),
                ('suggestContent', models.TextField(default='', help_text='建议内容', verbose_name='建议内容')),
            ],
            options={
                'verbose_name': '建议',
                'verbose_name_plural': '建议',
            },
        ),
    ]
