# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='多个领域', max_length=50, verbose_name='作者')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('identify', models.CharField(default='', max_length=200, verbose_name='MD5')),
                ('digest', models.CharField(default='', max_length=200, verbose_name='摘要')),
                ('category', models.IntegerField(choices=[(3, 'Python'), (5, 'TypeScript'), (4, 'JavaScript'), (1, 'OC'), (2, 'Swift')], verbose_name='分类')),
                ('body', models.TextField(default='', verbose_name='文章内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '博客',
                'verbose_name': '博客',
            },
        ),
    ]
