# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_remove_blogmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default='', max_length=100, verbose_name='分类'),
        ),
    ]
